/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.philips.gdl;

import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author efsantos
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }
    private static List<String> nomeObjetos = new ArrayList<String>();
    private String dsNomeTabelaLog = "SO";
    private String dsScriptTabelaLog
            = "CREATE SEQUENCE " + dsNomeTabelaLog + "_seq START WITH 1; \n"
            + "CREATE TABLE " + dsNomeTabelaLog + " (\n"
            + "ID           NUMBER(10),\n"
            + "	DS_LOG VARCHAR2(4000),\n"
            + "	DT_DATA DATE);"
            + "ALTER TABLE " + dsNomeTabelaLog + " ADD (\n"
            + "CONSTRAINT " + dsNomeTabelaLog + "_pk PRIMARY KEY (ID));";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tpAbaPane = new javax.swing.JTabbedPane();
        tbAbaObjeto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsScriptOriginal = new javax.swing.JTextArea();
        objetoBtAddVariavel = new javax.swing.JToggleButton();
        objetoBtRemoveVariavel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaVariaveis = new javax.swing.JList();
        objetoNmObjeto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        objetoNmTabelaLog = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        objetoDsCreateTable = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        objetoBtnGerar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        objetoDsScriptSaida = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        objetoBtAtualiza = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        checkBoxQuebra1 = new javax.swing.JLabel();
        checkBoxQuebra3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jchboxStackTrace = new javax.swing.JCheckBox();
        objetoJrbDias = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        objetoJrbMaskCompleta = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        checkBoxQuebra2 = new javax.swing.JLabel();
        txtNmUsuarioP = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        checkBoxQuebra = new javax.swing.JLabel();
        objetoJrbSemMask = new javax.swing.JRadioButton();
        jchboxCommitInsert = new javax.swing.JCheckBox();
        jchboxQuebraLinha = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        objetoDsScriptLimpar = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        objetoJrbHoras = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        tbAbaTabela = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        checkBoxQuebra5 = new javax.swing.JLabel();
        checkBoxQuebra7 = new javax.swing.JLabel();
        jchboxStackTrace1 = new javax.swing.JCheckBox();
        jchboxQuebraLinha1 = new javax.swing.JCheckBox();
        jSeparator11 = new javax.swing.JSeparator();
        tabelaTxtNmUsuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        tabelaJrbHoras1 = new javax.swing.JRadioButton();
        tabelaJrbDias1 = new javax.swing.JRadioButton();
        tabelaJrBMaskCompleta1 = new javax.swing.JRadioButton();
        tabelaJrbSemMask1 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        tabelaBtRemoveVariavel = new javax.swing.JButton();
        tabelaBtAddVariavel = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaListVariaveis = new javax.swing.JList();
        nmTabelaLog1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tabelaBtAtualiza = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelaDsCreateTable = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        nmTabelaTxt = new javax.swing.JTextField();
        tabelaLabel = new javax.swing.JLabel();
        tabelaBtGerarTrigger = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabelaDsTrigger = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tabelaDsDeleteTable = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de logs");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        dsScriptOriginal.setColumns(20);
        dsScriptOriginal.setRows(5);
        jScrollPane1.setViewportView(dsScriptOriginal);

        objetoBtAddVariavel.setText("+");
        objetoBtAddVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objetoBtAddVariavelActionPerformed(evt);
            }
        });

        objetoBtRemoveVariavel.setText("-");
        objetoBtRemoveVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objetoBtRemoveVariavelActionPerformed(evt);
            }
        });

        listaVariaveis.setModel(new javax.swing.AbstractListModel() {
            String variaveis[] = nomeObjetos.toArray(new String[0]);
            //nomeObjetos.toArray(new String[nomeObjetos.size()]);
            public int getSize() { return variaveis.length; }
            public Object getElementAt(int i) { return variaveis[i]; }
        });
        jScrollPane2.setViewportView(listaVariaveis);

        objetoNmObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objetoNmObjetoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome objeto.");

        objetoNmTabelaLog.setText("SO");
        objetoNmTabelaLog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                objetoNmTabelaLogKeyTyped(evt);
            }
        });

        jLabel2.setText("Nome da tabela de log (Exemplo : SO180000)");

        jLabel3.setText("Made by Eduardo Felipe dos Santos.");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("Variáveis para incluir nos logs");

        jLabel5.setText("Script original");

        objetoDsCreateTable.setColumns(20);
        objetoDsCreateTable.setRows(5);
        jScrollPane3.setViewportView(objetoDsCreateTable);

        jLabel6.setText("Script de criação de tabela de log");

        objetoBtnGerar.setText("GERAR SCRIPT COM LOGS");
        objetoBtnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objetoBtnGerarActionPerformed(evt);
            }
        });

        objetoDsScriptSaida.setColumns(20);
        objetoDsScriptSaida.setRows(5);
        jScrollPane4.setViewportView(objetoDsScriptSaida);

        jLabel7.setText("Saída de script");

        objetoBtAtualiza.setText("Refresh");
        objetoBtAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objetoBtAtualizaActionPerformed(evt);
            }
        });

        jLabel10.setText("NM_USUARIO_P  for:");

        checkBoxQuebra1.setText("Commit depois insert");

        checkBoxQuebra3.setText("Deletar tabela e sequences");

        jLabel8.setText("Máscara para datas");

        jchboxStackTrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchboxStackTraceActionPerformed(evt);
            }
        });

        buttonGroup1.add(objetoJrbDias);
        objetoJrbDias.setText("dd/mm/yyyy");

        buttonGroup1.add(objetoJrbMaskCompleta);
        objetoJrbMaskCompleta.setText("dd/mm/yyyy h24:mi:ss");

        checkBoxQuebra2.setText("Incluir StackTrace");

        checkBoxQuebra.setText("Quebra Linha");

        buttonGroup1.add(objetoJrbSemMask);
        objetoJrbSemMask.setText("Sem máscara");

        jchboxCommitInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchboxCommitInsertActionPerformed(evt);
            }
        });

        jchboxQuebraLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchboxQuebraLinhaActionPerformed(evt);
            }
        });

        objetoDsScriptLimpar.setColumns(20);
        objetoDsScriptLimpar.setRows(5);
        jScrollPane5.setViewportView(objetoDsScriptLimpar);

        jLabel11.setText("(Vazio para nada)");

        buttonGroup1.add(objetoJrbHoras);
        objetoJrbHoras.setText("h24:mi:ss");

        jLabel9.setText("Cair no log quando");

        javax.swing.GroupLayout tbAbaObjetoLayout = new javax.swing.GroupLayout(tbAbaObjeto);
        tbAbaObjeto.setLayout(tbAbaObjetoLayout);
        tbAbaObjetoLayout.setHorizontalGroup(
            tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(objetoBtnGerar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tbAbaObjetoLayout.createSequentialGroup()
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                                .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(objetoNmTabelaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(objetoBtAtualiza))
                            .addComponent(objetoNmObjeto)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbAbaObjetoLayout.createSequentialGroup()
                                .addComponent(objetoBtAddVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(objetoBtRemoveVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(checkBoxQuebra3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbAbaObjetoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jchboxStackTrace)
                            .addComponent(jchboxCommitInsert)
                            .addComponent(jchboxQuebraLinha)))
                    .addComponent(txtNmUsuarioP)
                    .addComponent(jSeparator7)
                    .addComponent(objetoJrbMaskCompleta)
                    .addComponent(objetoJrbSemMask)
                    .addComponent(objetoJrbDias)
                    .addComponent(checkBoxQuebra1)
                    .addComponent(checkBoxQuebra)
                    .addComponent(checkBoxQuebra2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(objetoJrbHoras))
                .addGap(13, 13, 13))
        );
        tbAbaObjetoLayout.setVerticalGroup(
            tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jScrollPane2))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                                .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(objetoBtAddVariavel)
                                        .addComponent(objetoBtRemoveVariavel))
                                    .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                                        .addComponent(objetoNmObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(objetoNmTabelaLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(objetoBtAtualiza))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(objetoBtnGerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(objetoJrbSemMask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(objetoJrbMaskCompleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(objetoJrbDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(objetoJrbHoras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNmUsuarioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchboxQuebraLinha)
                            .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                                .addComponent(checkBoxQuebra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchboxCommitInsert)
                            .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                                .addComponent(checkBoxQuebra1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbAbaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbAbaObjetoLayout.createSequentialGroup()
                                .addComponent(checkBoxQuebra2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxQuebra3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jchboxStackTrace))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(6, 6, 6))
        );

        tpAbaPane.addTab("Objetos", tbAbaObjeto);

        checkBoxQuebra5.setText("Incluir StackTrace");

        checkBoxQuebra7.setText("Quebra Linha");

        jchboxStackTrace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchboxStackTrace1ActionPerformed(evt);
            }
        });

        jchboxQuebraLinha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchboxQuebraLinha1ActionPerformed(evt);
            }
        });

        jLabel12.setText("(Vazio para nada)");

        jLabel14.setText("Cair no log quando NM_USUARIO  for:");

        buttonGroup1.add(tabelaJrbHoras1);
        tabelaJrbHoras1.setText("h24:mi:ss");

        buttonGroup1.add(tabelaJrbDias1);
        tabelaJrbDias1.setText("dd/mm/yyyy");

        buttonGroup1.add(tabelaJrBMaskCompleta1);
        tabelaJrBMaskCompleta1.setText("dd/mm/yyyy h24:mi:ss");

        buttonGroup1.add(tabelaJrbSemMask1);
        tabelaJrbSemMask1.setText("Sem máscara");

        jLabel15.setText("Máscara para datas");

        tabelaBtRemoveVariavel.setText("-");
        tabelaBtRemoveVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaBtRemoveVariavelActionPerformed(evt);
            }
        });

        tabelaBtAddVariavel.setText("+");
        tabelaBtAddVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaBtAddVariavelActionPerformed(evt);
            }
        });

        jLabel16.setText("Variáveis da tabela para incluir nos logs");

        tabelaListVariaveis.setModel(new javax.swing.AbstractListModel() {
            String variaveis[] = nomeObjetos.toArray(new String[0]);
            //nomeObjetos.toArray(new String[nomeObjetos.size()]);
            public int getSize() { return variaveis.length; }
            public Object getElementAt(int i) { return variaveis[i]; }
        });
        jScrollPane7.setViewportView(tabelaListVariaveis);

        nmTabelaLog1.setText("SO");
        nmTabelaLog1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nmTabelaLog1KeyTyped(evt);
            }
        });

        jLabel18.setText("Nome da tabela de log (Exemplo : SO180000)");

        tabelaBtAtualiza.setText("Refresh");
        tabelaBtAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaBtAtualizaActionPerformed(evt);
            }
        });

        jLabel19.setText("Script de criação de tabela de log");

        tabelaDsCreateTable.setColumns(20);
        tabelaDsCreateTable.setRows(5);
        jScrollPane8.setViewportView(tabelaDsCreateTable);

        jLabel21.setText("Made by Eduardo Felipe dos Santos.");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        nmTabelaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmTabelaTxtActionPerformed(evt);
            }
        });

        tabelaLabel.setText("Nome da Tabela");

        tabelaBtGerarTrigger.setText("Gerar Trigger!");
        tabelaBtGerarTrigger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaBtGerarTriggerActionPerformed(evt);
            }
        });

        tabelaDsTrigger.setColumns(20);
        tabelaDsTrigger.setRows(5);
        jScrollPane9.setViewportView(tabelaDsTrigger);

        jLabel20.setText("Saída trigger criada");

        tabelaDsDeleteTable.setColumns(20);
        tabelaDsDeleteTable.setRows(5);
        jScrollPane10.setViewportView(tabelaDsDeleteTable);

        jLabel22.setText("Script para excluir a tabela de logs e a trigger criada");

        jTextField1.setText("NR_SEQUENCIA");

        jLabel17.setText("Chave primária, (deixar vazio se mais de uma).");

        javax.swing.GroupLayout tbAbaTabelaLayout = new javax.swing.GroupLayout(tbAbaTabela);
        tbAbaTabela.setLayout(tbAbaTabelaLayout);
        tbAbaTabelaLayout.setHorizontalGroup(
            tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                        .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmTabelaTxt)
                            .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbAbaTabelaLayout.createSequentialGroup()
                                        .addComponent(tabelaBtAddVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tabelaBtRemoveVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jTextField1)
                                    .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                                        .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))
                                        .addGap(0, 6, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator12)
                                    .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(tabelaTxtNmUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                                    .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                                        .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkBoxQuebra7)
                                            .addComponent(checkBoxQuebra5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                        .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchboxStackTrace1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jchboxQuebraLinha1, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                                        .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tabelaJrBMaskCompleta1)
                                            .addComponent(tabelaJrbSemMask1)
                                            .addComponent(tabelaJrbDias1)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel15)
                                            .addComponent(tabelaJrbHoras1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE))
                                    .addComponent(jSeparator8)
                                    .addComponent(jSeparator10)))
                            .addComponent(jScrollPane8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbAbaTabelaLayout.createSequentialGroup()
                                .addComponent(nmTabelaLog1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabelaBtAtualiza))
                            .addComponent(jScrollPane10)
                            .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabelaBtGerarTrigger, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                        .addComponent(tabelaLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap())
        );
        tbAbaTabelaLayout.setVerticalGroup(
            tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabelaLabel)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9)
                    .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                        .addComponent(nmTabelaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tabelaBtRemoveVariavel)
                                    .addComponent(tabelaBtAddVariavel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tbAbaTabelaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabelaJrbSemMask1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabelaJrBMaskCompleta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabelaJrbDias1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabelaJrbHoras1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabelaTxtNmUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxQuebra7)
                                    .addComponent(jchboxQuebraLinha1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxQuebra5)
                                    .addComponent(jchboxStackTrace1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbAbaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nmTabelaLog1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabelaBtAtualiza))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabelaBtGerarTrigger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpAbaPane.addTab("Tabelas", tbAbaTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAbaPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpAbaPane)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void objetoNmObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objetoNmObjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_objetoNmObjetoActionPerformed

    private void objetoNmTabelaLogKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_objetoNmTabelaLogKeyTyped

    }//GEN-LAST:event_objetoNmTabelaLogKeyTyped

    private void objetoBtAddVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objetoBtAddVariavelActionPerformed

        objetoAdicionaVariavel();
    }//GEN-LAST:event_objetoBtAddVariavelActionPerformed

    private void objetoBtRemoveVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objetoBtRemoveVariavelActionPerformed
        objetoRemoveVariavel();
    }//GEN-LAST:event_objetoBtRemoveVariavelActionPerformed

    private void objetoBtAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objetoBtAtualizaActionPerformed
        objetoAtualizaScript();
    }//GEN-LAST:event_objetoBtAtualizaActionPerformed

    private void objetoBtnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objetoBtnGerarActionPerformed
        objetoBtnGerarAction();

    }//GEN-LAST:event_objetoBtnGerarActionPerformed

    private void jchboxQuebraLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchboxQuebraLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchboxQuebraLinhaActionPerformed

    private void jchboxCommitInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchboxCommitInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchboxCommitInsertActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (evt.getClickCount() == 10) {
            Ee.inicia();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jchboxStackTraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchboxStackTraceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchboxStackTraceActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(null, "Não esqueça de compilar o objeto original sem logs, e deletar as tabelas e sequences criadas!", "Aviso", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_formWindowClosing

    private void tabelaBtGerarTriggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaBtGerarTriggerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaBtGerarTriggerActionPerformed

    private void nmTabelaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmTabelaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmTabelaTxtActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void tabelaBtAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaBtAtualizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaBtAtualizaActionPerformed

    private void nmTabelaLog1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmTabelaLog1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nmTabelaLog1KeyTyped

    private void tabelaBtAddVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaBtAddVariavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaBtAddVariavelActionPerformed

    private void tabelaBtRemoveVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaBtRemoveVariavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaBtRemoveVariavelActionPerformed

    private void jchboxQuebraLinha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchboxQuebraLinha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchboxQuebraLinha1ActionPerformed

    private void jchboxStackTrace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchboxStackTrace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchboxStackTrace1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private telaPrincipal tela;

            public void run() {
                tela = new telaPrincipal();
                tela.setVisible(true);
                tela.objetoAtualizaScript();
                tela.nomeObjetos.add("nm_usuario_p");
                tela.objetoAtualizaLista();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel checkBoxQuebra;
    private javax.swing.JLabel checkBoxQuebra1;
    private javax.swing.JLabel checkBoxQuebra2;
    private javax.swing.JLabel checkBoxQuebra3;
    private javax.swing.JLabel checkBoxQuebra5;
    private javax.swing.JLabel checkBoxQuebra7;
    private javax.swing.JTextArea dsScriptOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox jchboxCommitInsert;
    private javax.swing.JCheckBox jchboxQuebraLinha;
    private javax.swing.JCheckBox jchboxQuebraLinha1;
    private javax.swing.JCheckBox jchboxStackTrace;
    private javax.swing.JCheckBox jchboxStackTrace1;
    private javax.swing.JList listaVariaveis;
    private javax.swing.JTextField nmTabelaLog1;
    private javax.swing.JTextField nmTabelaTxt;
    private javax.swing.JToggleButton objetoBtAddVariavel;
    private javax.swing.JToggleButton objetoBtAtualiza;
    private javax.swing.JButton objetoBtRemoveVariavel;
    private javax.swing.JButton objetoBtnGerar;
    private javax.swing.JTextArea objetoDsCreateTable;
    private javax.swing.JTextArea objetoDsScriptLimpar;
    private javax.swing.JTextArea objetoDsScriptSaida;
    private javax.swing.JRadioButton objetoJrbDias;
    private javax.swing.JRadioButton objetoJrbHoras;
    private javax.swing.JRadioButton objetoJrbMaskCompleta;
    private javax.swing.JRadioButton objetoJrbSemMask;
    private javax.swing.JTextField objetoNmObjeto;
    private javax.swing.JTextField objetoNmTabelaLog;
    private javax.swing.JToggleButton tabelaBtAddVariavel;
    private javax.swing.JToggleButton tabelaBtAtualiza;
    private javax.swing.JButton tabelaBtGerarTrigger;
    private javax.swing.JButton tabelaBtRemoveVariavel;
    private javax.swing.JTextArea tabelaDsCreateTable;
    private javax.swing.JTextArea tabelaDsDeleteTable;
    private javax.swing.JTextArea tabelaDsTrigger;
    private javax.swing.JRadioButton tabelaJrBMaskCompleta1;
    private javax.swing.JRadioButton tabelaJrbDias1;
    private javax.swing.JRadioButton tabelaJrbHoras1;
    private javax.swing.JRadioButton tabelaJrbSemMask1;
    private javax.swing.JLabel tabelaLabel;
    private javax.swing.JList tabelaListVariaveis;
    private javax.swing.JTextField tabelaTxtNmUsuario;
    private javax.swing.JPanel tbAbaObjeto;
    private javax.swing.JPanel tbAbaTabela;
    private javax.swing.JTabbedPane tpAbaPane;
    private javax.swing.JTextField txtNmUsuarioP;
    // End of variables declaration//GEN-END:variables
    public void objetoAtualizaScript() {
        dsNomeTabelaLog = nvl(objetoNmTabelaLog.getText(), "SO");
        dsScriptTabelaLog = "CREATE SEQUENCE " + dsNomeTabelaLog + "_seq START WITH 1; \n"
                + "CREATE TABLE " + dsNomeTabelaLog + " (\n"
                + "ID           NUMBER(10),\n"
                + "	DS_LOG VARCHAR2(4000),\n"
                + "	DT_DATA DATE);"
                + "ALTER TABLE " + dsNomeTabelaLog + " ADD (\n"
                + "CONSTRAINT " + dsNomeTabelaLog + "_pk PRIMARY KEY (ID));";
        objetoDsCreateTable.setText(dsScriptTabelaLog);

        String dsScriptExclusaoTabela = "DROP SEQUENCE " + dsNomeTabelaLog + "_seq;\n"
                + "truncate table  " + dsNomeTabelaLog + ";\n"
                + "drop table  " + dsNomeTabelaLog + ";";
        objetoDsScriptLimpar.setText(dsScriptExclusaoTabela);
    }

    public static String nvl(String value, String alternateValue) {
        if (value == null) {
            return alternateValue;
        }
        return value;
    }

    public void objetoAtualizaLista() {
        listaVariaveis.setModel(new javax.swing.AbstractListModel() {
            String variaveis[] = nomeObjetos.toArray(new String[0]);

            public int getSize() {
                return variaveis.length;
            }

            public Object getElementAt(int i) {
                return variaveis[i];
            }
        });
    }

    private void objetoAdicionaVariavel() {
        String valor = nvl(JOptionPane.showInputDialog("Nome da variável"), "ds");
        this.nomeObjetos.add(valor);
        objetoAtualizaLista();

    }

    private void objetoRemoveVariavel() {
        int index = listaVariaveis.getSelectedIndex();
        if (index > -1) {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente remover essa variável?") == JOptionPane.YES_OPTION) {
                this.nomeObjetos.remove(index);
                objetoAtualizaLista();
            }
        }
    }

    private String objetoMontaVariavelLog() {
        String quebraLinha = jchboxQuebraLinha.isSelected() ? "||  CHR(10)" : " ";

        String vars = "|| ' linha:' || $$plsql_line " + quebraLinha;
        for (String objs : nomeObjetos) {
            vars += " || '| " + objs + ": ' || " + objetoMontaValor(objs) + quebraLinha;
        }
        if (jchboxStackTrace.isSelected()) {
            vars += " || ' | Stacktrace: '||  CHR(10) || SUBSTR(DBMS_UTILITY.FORMAT_CALL_STACK,1,2000)";
        }
        //return ((txtNmUsuarioP.getText() != null && !txtNmUsuarioP.getText().trim().isEmpty()) ? "if(nm_usuario_p = '" + txtNmUsuarioP.getText() + "') then " : "") + "INSERT INTO " + nvl(dsNomeTabelaLog, "NOME_TABELA_VAZIA") + " VALUES (('" + nvl(nmObjeto.getText(), "NOME_OBJETO_VAZIO") + "'" + vars + ") , sysdate)" + (this.jchboxCommitInsert.isSelected() ? ";commit" : "") + ";" + ((txtNmUsuarioP.getText() != null && !txtNmUsuarioP.getText().trim().isEmpty()) ? "end if;" : "");
        String retorno = "";
        if ((txtNmUsuarioP.getText() != null && !txtNmUsuarioP.getText().trim().isEmpty())) {
            retorno += "if(nm_usuario_p = '" + txtNmUsuarioP.getText() + "') then ";
        }
        retorno += "INSERT INTO " + nvl(dsNomeTabelaLog, "NOME_TABELA_VAZIA") + " VALUES (" + dsNomeTabelaLog + "_seq.nextval,('" + nvl(objetoNmObjeto.getText(), "NOME_OBJETO_VAZIO") + "'" + vars + ") , sysdate)";
        if (this.jchboxCommitInsert.isSelected()) {
            retorno += ";commit";
        }
        retorno += ";";
        if ((txtNmUsuarioP.getText() != null && !txtNmUsuarioP.getText().trim().isEmpty())) {
            retorno += "end if;";
        }
        return retorno;
    }

    private String objetoMontaValor(String var) {
        String retorno = var != null ? var.toUpperCase() : null;
        if (retorno != null && retorno.startsWith("DT_") && (retorno.endsWith("_P") || retorno.endsWith("_W"))) {
            if (this.objetoJrbMaskCompleta.isSelected()) {
                retorno = "to_char(" + var + ",'dd/mm/yyyy hh24:mi:ss')";
            } else if (this.objetoJrbDias.isSelected()) {
                retorno = "to_char(" + var + ",'dd/mm/yyyy')";
            } else if (this.objetoJrbHoras.isSelected()) {
                retorno = "to_char(" + var + ",'hh24:mi:ss')";
            }
        }
        return retorno;
    }

    private void objetoBtnGerarAction() {
        objetoAtualizaScript();
        String textoOriginal = dsScriptOriginal.getText();
        if (textoOriginal == null || textoOriginal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Aviso, o campo script original está vazio.");
            return;
        }
        String stringLog = objetoMontaVariavelLog();
        System.out.println(stringLog);
        objetoDsScriptSaida.setText(textoOriginal.replace("then", " then \n " + stringLog));
        objetoDsScriptSaida.setText(objetoDsScriptSaida.getText().replace("THEN", " THEN \n " + stringLog));
        objetoDsScriptSaida.setText(objetoDsScriptSaida.getText().replace("else", " else \n " + stringLog));
        objetoDsScriptSaida.setText(objetoDsScriptSaida.getText().replace("ELSE", " ELSE \n " + stringLog));
    }

    private void janelaVariavel() {
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("x:"));
        myPanel.add(xField);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("y:"));
        myPanel.add(yField);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Please Enter X and Y Values", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println("x value: " + xField.getText());
            System.out.println("y value: " + yField.getText());
        }
    }
}


