/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.philips.gdl;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author efsantos
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }
    private static List<String> nomeObjetos = new ArrayList<String>();
    private String dsNomeTabelaLog = "SO";
    private String dsScriptTabelaLog = "CREATE	TABLE	" + dsNomeTabelaLog + " (\n"
            + "	DS_LOG VARCHAR2(4000),\n"
            + "	DT_DATA DATE);";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void atualizaScript() {
        dsNomeTabelaLog = nvl(nmTabelaLog.getText(), "SO");
        dsScriptTabelaLog = "CREATE TABLE " + nvl(dsNomeTabelaLog, "SO") + " (\n"
                + " DS_LOG VARCHAR2(4000),\n"
                + " DT_DATA DATE);";
        dsCreateTable.setText(dsScriptTabelaLog);
    }

    public static String nvl(String value, String alternateValue) {
        if (value == null) {
            return alternateValue;
        }
        return value;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsScriptOriginal = new javax.swing.JTextArea();
        btAddVariavel = new javax.swing.JToggleButton();
        btRemoveVariavel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaVariaveis = new javax.swing.JList();
        nmObjeto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nmTabelaLog = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dsCreateTable = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        dsScriptSaida = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btAtualiza = new javax.swing.JToggleButton();
        jrbSemMask = new javax.swing.JRadioButton();
        jrBMaskCompleta = new javax.swing.JRadioButton();
        jrbDias = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jrbHoras = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNmUsuarioP = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jchboxQuebraLinha = new javax.swing.JCheckBox();
        checkBoxQuebra = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        checkBoxQuebra1 = new javax.swing.JLabel();
        jchboxCommitInsert = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de logs");
        setResizable(false);

        dsScriptOriginal.setColumns(20);
        dsScriptOriginal.setRows(5);
        jScrollPane1.setViewportView(dsScriptOriginal);

        btAddVariavel.setText("+");
        btAddVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddVariavelActionPerformed(evt);
            }
        });

        btRemoveVariavel.setText("-");
        btRemoveVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveVariavelActionPerformed(evt);
            }
        });

        listaVariaveis.setModel(new javax.swing.AbstractListModel() {
            String variaveis[] = nomeObjetos.toArray(new String[0]);
            //nomeObjetos.toArray(new String[nomeObjetos.size()]);
            public int getSize() { return variaveis.length; }
            public Object getElementAt(int i) { return variaveis[i]; }
        });
        jScrollPane2.setViewportView(listaVariaveis);

        nmObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmObjetoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome objeto.");

        nmTabelaLog.setText("SO");
        nmTabelaLog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nmTabelaLogKeyTyped(evt);
            }
        });

        jLabel2.setText("Nome da tabela de log (Exemplo : SO180000)");

        jLabel3.setText("Made by Eduardo Felipe dos Santos.");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("Variáveis para incluir nos logs");

        jLabel5.setText("Script original");

        dsCreateTable.setColumns(20);
        dsCreateTable.setRows(5);
        jScrollPane3.setViewportView(dsCreateTable);

        jLabel6.setText("Script de criação de tabela de log");

        btnGerar.setText("GERAR SCRIPT COM LOGS");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        dsScriptSaida.setColumns(20);
        dsScriptSaida.setRows(5);
        jScrollPane4.setViewportView(dsScriptSaida);

        jLabel7.setText("Saída de script");

        btAtualiza.setText("Refresh");
        btAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(btnGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmObjeto)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nmTabelaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAtualiza)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAddVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btRemoveVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nmObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nmTabelaLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtualiza))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAddVariavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoveVariavel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(6, 6, 6))
        );

        buttonGroup1.add(jrbSemMask);
        jrbSemMask.setSelected(true);
        jrbSemMask.setText("Sem máscara");

        buttonGroup1.add(jrBMaskCompleta);
        jrBMaskCompleta.setText("dd/mm/yyyy h24:mi:ss");

        buttonGroup1.add(jrbDias);
        jrbDias.setText("dd/mm/yyyy");

        jLabel8.setText("Máscara para datas");

        buttonGroup1.add(jrbHoras);
        jrbHoras.setText("h24:mi:ss");

        jLabel9.setText("Cair no log quando");

        jLabel10.setText("NM_USUARIO_P  for:");

        jLabel11.setText("(Vazio para nada)");

        jchboxQuebraLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchboxQuebraLinhaActionPerformed(evt);
            }
        });

        checkBoxQuebra.setText("Quebra Linha");

        checkBoxQuebra1.setText("Commit depois insert");

        jchboxCommitInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchboxCommitInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrBMaskCompleta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addComponent(jLabel8))
                                        .addComponent(jrbSemMask, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrbDias, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrbHoras, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtNmUsuarioP)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(checkBoxQuebra)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(checkBoxQuebra1)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jchboxCommitInsert)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jchboxQuebraLinha)
                                .addGap(65, 65, 65))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSemMask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrBMaskCompleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbHoras)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNmUsuarioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxQuebra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchboxQuebraLinha)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxQuebra1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchboxCommitInsert)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nmObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmObjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmObjetoActionPerformed

    private void nmTabelaLogKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmTabelaLogKeyTyped

    }//GEN-LAST:event_nmTabelaLogKeyTyped

    private void btAddVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddVariavelActionPerformed

        adicionaVariavel();
    }//GEN-LAST:event_btAddVariavelActionPerformed

    private void btRemoveVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveVariavelActionPerformed
        removeVariavel();
    }//GEN-LAST:event_btRemoveVariavelActionPerformed

    private void btAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizaActionPerformed
        atualizaScript();
    }//GEN-LAST:event_btAtualizaActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        atualizaScript();
        String textoOriginal = dsScriptOriginal.getText();
        if (textoOriginal == null || textoOriginal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Aviso, o campo script original está vazio.");
            return;
        }
        String stringLog = montaVariavelLog();
        System.out.println(stringLog);
        dsScriptSaida.setText(textoOriginal.replace(" then", " then \n " + stringLog));
    }//GEN-LAST:event_btnGerarActionPerformed

    private void jchboxQuebraLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchboxQuebraLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchboxQuebraLinhaActionPerformed

    private void jchboxCommitInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchboxCommitInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchboxCommitInsertActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(evt.getClickCount() == 10){
            Ee.inicia();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private telaPrincipal tela;

            public void run() {
                tela = new telaPrincipal();
                tela.setVisible(true);
                tela.atualizaScript();
                tela.nomeObjetos.add("nm_usuario_p");
                tela.atualizaLista();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAddVariavel;
    private javax.swing.JToggleButton btAtualiza;
    private javax.swing.JButton btRemoveVariavel;
    private javax.swing.JButton btnGerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel checkBoxQuebra;
    private javax.swing.JLabel checkBoxQuebra1;
    private javax.swing.JTextArea dsCreateTable;
    private javax.swing.JTextArea dsScriptOriginal;
    private javax.swing.JTextArea dsScriptSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JCheckBox jchboxCommitInsert;
    private javax.swing.JCheckBox jchboxQuebraLinha;
    private javax.swing.JRadioButton jrBMaskCompleta;
    private javax.swing.JRadioButton jrbDias;
    private javax.swing.JRadioButton jrbHoras;
    private javax.swing.JRadioButton jrbSemMask;
    private javax.swing.JList listaVariaveis;
    private javax.swing.JTextField nmObjeto;
    private javax.swing.JTextField nmTabelaLog;
    private javax.swing.JTextField txtNmUsuarioP;
    // End of variables declaration//GEN-END:variables

    public void atualizaLista() {
        listaVariaveis.setModel(new javax.swing.AbstractListModel() {
            String variaveis[] = nomeObjetos.toArray(new String[0]);

            public int getSize() {
                return variaveis.length;
            }

            public Object getElementAt(int i) {
                return variaveis[i];
            }
        });
    }

    private void adicionaVariavel() {
        String valor = nvl(JOptionPane.showInputDialog("Nome da variável"), "ds");
        this.nomeObjetos.add(valor);
        atualizaLista();

    }

    private void removeVariavel() {
        int index = listaVariaveis.getSelectedIndex();
        if (index > -1) {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente remover essa variável?") == JOptionPane.YES_OPTION) {
                this.nomeObjetos.remove(index);
                atualizaLista();
            }
        }
    }

    private String montaVariavelLog() {
        String quebraLinha = jchboxQuebraLinha.isSelected() ? "||  CHR(10)" : " ";

        String vars = "|| ' linha:' || $$plsql_line " + quebraLinha;
        for (String objs : nomeObjetos) {
            vars = vars + " || '| " + objs + ": ' || " + montaValor(objs) + quebraLinha;
        }
        //return ((txtNmUsuarioP.getText() != null && !txtNmUsuarioP.getText().trim().isEmpty()) ? "if(nm_usuario_p = '" + txtNmUsuarioP.getText() + "') then " : "") + "INSERT INTO " + nvl(dsNomeTabelaLog, "NOME_TABELA_VAZIA") + " VALUES (('" + nvl(nmObjeto.getText(), "NOME_OBJETO_VAZIO") + "'" + vars + ") , sysdate)" + (this.jchboxCommitInsert.isSelected() ? ";commit" : "") + ";" + ((txtNmUsuarioP.getText() != null && !txtNmUsuarioP.getText().trim().isEmpty()) ? "end if;" : "");
        String retorno = "";
        if ((txtNmUsuarioP.getText() != null && !txtNmUsuarioP.getText().trim().isEmpty())) {
            retorno += "if(nm_usuario_p = '" + txtNmUsuarioP.getText() + "') then ";
        }
        retorno += "INSERT INTO " + nvl(dsNomeTabelaLog, "NOME_TABELA_VAZIA") + " VALUES (('" + nvl(nmObjeto.getText(), "NOME_OBJETO_VAZIO") + "'" + vars + ") , sysdate)";
        if (this.jchboxCommitInsert.isSelected()) {
            retorno += ";commit";
        }
        retorno += ";";
        if ((txtNmUsuarioP.getText() != null && !txtNmUsuarioP.getText().trim().isEmpty())) {
            retorno += "end if;";
        }
        return retorno;
    }

    private String montaValor(String var) {
        String retorno = var != null ? var.toUpperCase() : null;
        if (retorno != null && retorno.startsWith("DT_") && (retorno.endsWith("_P") || retorno.endsWith("_W"))) {
            if (this.jrBMaskCompleta.isSelected()) {
                retorno = "to_char(" + var + ",'dd/mm/yyyy hh24:mi:ss')";
            } else if (this.jrbDias.isSelected()) {
                retorno = "to_char(" + var + ",'dd/mm/yyyy')";
            } else if (this.jrbHoras.isSelected()) {
                retorno = "to_char(" + var + ",'hh24:mi:ss')";
            }
        }
        return retorno;
    }
}
